# Generated by Django 4.0.5 on 2022-06-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_created_at_category_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
